<div style="color:#483838; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Numpy_part4</h1>
</div>

- __28)all & any in python__
- __29)all & any in numpy__
- __30)unique__
- __31)sort__  
- __32)in1d__

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>28)all & any in python</h2>
</div>

- `all` and `any` are two python built in functions. 
- any returns True, if any of items is True or numbers.
- any returns False if all of items are false, zero or we have empty array.
- `all` returns True if all elemnts of array are True or number.
- It returns False if all elements of the array are False, 0 or we have empty array.

In [1]:
import numpy as np
a = np.array([True, True, False])
b = np.array([False, False, False])
c = np.array([])

In [2]:
a.any()

True

In [3]:
a.all()

False

In [4]:
b.any()

False

In [5]:
b.all()

False

In [6]:
c.any()

False

In [7]:
c.all()

True

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>29)all & any in numpy</h2>
</div>

- these are exactly like all and any in python.

In [8]:
a = np.array([0, 2, -3])

In [9]:
np.any(b)

False

In [10]:
b = np.array([0, 0, 0])

In [11]:
np.any(b)

False

In [12]:
c = np.array([])

In [13]:
np.any(c)

False

In [14]:
np.all(b)

False

In [15]:
c = [8, 2, -3]

In [16]:
np.all(c)

True

In [17]:
# unique

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>30)unique </h2>
</div>

- Returns the sorted unique elements of an array in order.

In [18]:
arr = np.array([3, 4, 7, 4, 2, 1, 3, 5, 4, 4])
np.unique(arr)

array([1, 2, 3, 4, 5, 7])

In [19]:
a , i = np.unique(arr, return_index=True)  #a is the list of unique values, and i is the first index of each one.

In [20]:
a

array([1, 2, 3, 4, 5, 7])

In [21]:
i

array([5, 4, 0, 1, 7, 2], dtype=int64)

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>31)sort </h2>
</div>

ex1)

In [22]:
arr = np.array([3, 4, 7, 4, 2, 1, 3, 5, 4, 4])
arr = np.sort(arr)
arr

array([1, 2, 3, 3, 4, 4, 4, 4, 5, 7])

ex2)

In [23]:
data = [('ali',12.5,35) , ('sara',18.75,27),('taha',16.25,27)]
type(data)

list

In [24]:
d = [('name','S10'), ('score',float) , ('age',int)]

In [25]:
arr = np.array(data, dtype=d)

In [26]:
np.sort(arr, order='age')

array([(b'sara', 18.75, 27), (b'taha', 16.25, 27), (b'ali', 12.5 , 35)],
      dtype=[('name', 'S10'), ('score', '<f8'), ('age', '<i4')])

In [27]:
np.sort(arr, order='score')

array([(b'ali', 12.5 , 35), (b'taha', 16.25, 27), (b'sara', 18.75, 27)],
      dtype=[('name', 'S10'), ('score', '<f8'), ('age', '<i4')])

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>32)in1d </h2>
</div>

- in1d() function test whether each element of a 1-D array is also present in a second array and return a boolean array the same length as arr1 that is True where an element of arr1 is in arr2 and False otherwise.

In [28]:
x = np.array([7, 1, 4, 2, 5, 7])
y = [3, 4, 7]
np.in1d(x, y)

array([ True, False,  True, False, False,  True])

In [29]:
x = np.array([7, 1, 4, 2, 5, 7])
y = [3, 4, 7]
m = np.in1d(x, y)
x[m]

array([7, 4, 7])

In [30]:
x = np.array([7, 1, 4, 2, 5, 7])
y = [3, 4, 7]
m = np.in1d(x, y, invert=True)
x[m]

array([1, 2, 5])