<div style="color:#483838; padding:0px 10px; border-radius:5px; font-size:18px; text-align:center"><h1 style='margin:10px 5px'>Numpy_part3</h1>
</div>

- __21)Random module in Numpy__
        a_To create a random number between 0 and 1
        b_To create a matrix with random elements, between 0 and 1
        c_To create a tensor with random elements between 0 and 1
        d_random.random()
- __22)Produce random integer number__
- __23)Choose a number by chance from a list of numbers__  
- __24)produce random numbers with `uniform` distributions__
- __25)produce random numbers with `Normal` distributions__  
- __26)matrix invers__
- __27)Transpose__

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>21)Random module in Numpy</h2>
</div>

##### a_To create a random number between 0 and 1

In [1]:
import numpy as np
print(np.random.rand())     #a random number between 0 and 1
print(np.random.rand(2))    #a random vector

0.7254587950526907
[0.0154232  0.37954387]


##### b_To create a matrix with random elements, between 0 and 1

In [2]:
a = np.random.rand(3, 3)
a

array([[0.97249463, 0.24787138, 0.5542593 ],
       [0.55947022, 0.13335996, 0.35128128],
       [0.85611629, 0.21217216, 0.27212119]])

##### c_To create a tensor with random elements between 0 and 1

In [3]:
np.random.rand(2, 2, 3)

array([[[0.03449391, 0.31868055, 0.73555813],
        [0.83019507, 0.31447441, 0.39695792]],

       [[0.8755969 , 0.50457528, 0.37563557],
        [0.07330676, 0.29391554, 0.06525075]]])

##### d_random.random()

- We also can use **np.random.random()** to produce the above outputs.
- But we should put our dimensions in a tuple.

In [4]:
np.random.random()

0.4908076765875774

In [5]:
np.random.random((2, 2, 3))

array([[[0.08535747, 0.73719511, 0.47428702],
        [0.50766517, 0.12662197, 0.753864  ]],

       [[0.97227951, 0.8251763 , 0.28923275],
        [0.01726262, 0.17467423, 0.18248832]]])

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>22)Produce random integer number</h2>
</div>

- np.random.randint(low, high=None, size=None, dtype=int)

- Return random integers from `low` (inclusive) to `high` (exclusive).

In [6]:
np.random.randint(10)    #--> produce a random integer number from 0 to 9.

8

In [7]:
np.random.randint(1, 20, size = (2, 3, 3))

array([[[ 6,  3, 15],
        [13, 10, 10],
        [ 9, 11, 15]],

       [[18, 10, 17],
        [ 9,  5, 15],
        [ 8, 17, 12]]])

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>23)Choose a number by chance from a list of numbers</h2>
</div>

__`choice` : Choose a number by chance from a list of numbers. The list must be a vector, and must not have more dimensions.__

###### np.random.choice(lst, size of random numbers to be choosen.)

In [8]:
lst = np.random.randint(0, 20, size = (20,))
lst

array([ 1, 17, 11, 10, 15,  6,  5, 10,  8, 13, 16,  9, 16, 18,  4,  4, 16,
       19,  7,  6])

In [9]:
np.random.choice(lst,2)

array([11,  6])

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>24)produce random numbers with `uniform` distributions</h2>
</div>

- Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform.

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html?highlight=uniform#numpy.random.Generator.uniform

- np.random.uniform(low, high=, size))

In [10]:
uni = np.random.uniform(1,100,100_000)
uni

array([ 1.17927347, 56.40149348, 82.3352516 , ..., 43.89378146,
       77.7487063 , 32.97336742])

In [11]:
plt.hist(uni)
plt.show()

NameError: name 'plt' is not defined

In [ ]:
np.random.uniform(10, 20, size = (2, 3, 3))

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>25)produce random numbers with `Normal` distributions</h2>
</div>

- np.random.normal(mean or median, standard deviation , size=None)
- https://en.wikipedia.org/wiki/Normal_distribution

np.random.normal((loc=0.0, scale=1.0, size=None)) 
- loc:mean     scale:std

In [ ]:
nor = np.random.normal(0,.1,100_0000)

In [ ]:
import seaborn as sns
sns.histplot(nor,kde=True)
plt.show()

In [ ]:
np.random.normal(0,.3,(3,3))

-In Normal distribution, the most numbers are produced between (median and median + standard deviation) and (median and median - standard deviation)

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>26)matrix invers</h2>
</div>

In [ ]:
x = np.array([[1., 2.], [3., 4.]])

In [ ]:
from numpy.linalg import inv

In [ ]:
inv(x)

<div class="alert alert-info" style="color:black; padding:0px 10px; border-radius:5px;"><h2 style='margin:8px 3px; font-size:18px'>27)Transpose</h2>
</div>

### Matrix Transpose

In [ ]:
arr = np.arange(0,8).reshape(2,-1)
arr

- we can use array.T & np.swapaxes & np.Transpose to calculate transpose of an array.

In [ ]:
arr.T

- np.swapaxes(a, axis1, axis2)

In [ ]:
np.swapaxes(arr, 0, 1)

- https://numpy.org/doc/stable/reference/generated/numpy.transpose.html #numpy.transpose

In [ ]:
np.transpose(arr)

##### Tensor transpose

In [ ]:
z = np.arange(8).reshape((2, 2 , 2))
z

In [ ]:
np.swapaxes(z, 1, 2)

In [ ]:
np.swapaxes(z, 0, 1)

In [ ]:
np.transpose(z, (0, 2, 1))